### ISSUE TITLE
Error: User information is not found. Make sure the given Username exists and the account is public.

### ISSUE THREAD

**Issue by Tra2x** [russdreamer/instagram-followers-statistics#10]
Hi,
Script was working well, but since the last Update I always get this Error. Username is mentioned correctly and it doesn't matter if I upload with the user an old file or try to generate a new one. I always get this Error.
With my own profile all is working well.

Please tell me what kind of data I can forward you to analyse the Issue.
Thanks in advance

**Comment by russdreamer** [comment]
Hi, thanks, this info was enough to fix. Done

**Comment by Tra2x** [comment]
Thanks, I can confirm, that the fix is working :)
