### ISSUE TITLE
I don't see the button to follow random accounts

### ISSUE THREAD

**Issue by lugohtk** [russdreamer/instagram-followers-statistics#11]
the extension is incredible but I don't know why the option to follow random accounts doesn't appear

**Comment by russdreamer** [comment]
@lugohtk 

> the extension is incredible but I don't know why the option to follow random accounts doesn't appear

I've switched this off as this function is hard to maintain. Every time they change their API I have to create a new account to check it and in most cases, they ban it before I was able to log in and check. Now I have one to test, let's see if I'll manage it next few days.

**Comment by russdreamer** [comment]
@lugohtk random following is back

**Comment by lugohtk** [comment]
![Sin título](https://user-images.githubusercontent.com/112210418/187105165-b7357dfc-bde4-4b6a-b402-7fe5bda9b554.png)

**Comment by russdreamer** [comment]
@lugohtk did it follow new accounts? or no new accounts were added?

**Comment by russdreamer** [comment]
@lugohtk please try again. If the same error occurs - send me what error is written in the console tab. F12 in most browsers or check [here](https://appuals.com/open-browser-console/)
