### ISSUE TITLE
The button is not shown on Safari

### ISSUE THREAD

**Issue by koraykupe** [russdreamer/instagram-followers-statistics#12]
Hello,

I am using the script in Tampermonkey + Chrome, and it works fine. I can see the button on left. Today I tried it on Safari, but it doesn't show any button on my Instragram page. Is it a known issue or am I missing something?

**Comment by russdreamer** [comment]
Hey @koraykupe ,
No, it wasn't a known issue, thanks for reporting. The issue was related to browsers that don't support `trustedTypes` that is forced by chrome now. Added a fork for such browsers. 
Fixed, check it, please

**Comment by koraykupe** [comment]
I am sorry, but I didn't get how to update it. I can't manually edit the file you updated in Tampermonkey or maybe I am missing something.

**Comment by russdreamer** [comment]
@koraykupe my bad, there was an update issue. Fixed, but you can force it as tumpermonkey looks for updates once per day. Click [here](https://github.com/russdreamer/instagram-followers-statistics/raw/master/installation.user.js), press update button and check if all work as expected

**Comment by koraykupe** [comment]
Worked, thank you!
