### ISSUE TITLE
the open app button doesn't show up anymore (chrome v. 108)

### ISSUE THREAD

**Issue by ghost** [russdreamer/instagram-followers-statistics#13]
![image](https://user-images.githubusercontent.com/85667418/205460533-c2561aab-638f-48fd-a36e-4ae21fa74d4b.png)

**Comment by russdreamer** [comment]
@lucaciuc answer please following questions:
1) Was this script working before? If so, when did it stop working (approximately)?
2) What browser do you use?
3) What version of the browser? 
4) Any other errors in the console? 

Try also run in the console this and tell me the result:
`typeof trustedTypes !== 'undefined'`

**Comment by ghost** [comment]
1. yes, it was
2. chrome
3. 108.0.5359.95
4. no

adnotations:
![image](https://user-images.githubusercontent.com/85667418/205496230-e4640255-472a-4dd6-a870-b66d9caea5fc.png)
also i installed firefox portable and it seems to work there

**Comment by russdreamer** [comment]
You're right, the app stopped working in the latest chrome version 108. I'll take a look

**Comment by russdreamer** [comment]
@lucaciuc , 
The issue is solved, please [update the script](https://github.com/russdreamer/instagram-followers-statistics/raw/master/installation.user.js).
