### ISSUE TITLE
Error generating statistics 

### ISSUE THREAD

**Issue by 0julio** [russdreamer/instagram-followers-statistics#16]
![brave_7bbh3hACS9](https://user-images.githubusercontent.com/106554745/235487573-d6fd7c7f-b757-4a23-8cf2-7bca2a7e6992.png)

**Comment by russdreamer** [comment]
@Nuuzz what's the followers and followings size number in your account?

**Comment by snake302** [comment]
the same, less than 400 followers & less than 400 following

**Comment by 0julio** [comment]
> @Nuuzz what's the followers and followings size number in your account?

327 followers and 390 following

**Comment by russdreamer** [comment]
@snake302 @Nuuzz Should be solved. please check

**Comment by 0julio** [comment]
@russdreamer it seems to work, thank u 👍
