### ISSUE TITLE
new bag

### ISSUE THREAD

**Issue by neklik** [russdreamer/instagram-followers-statistics#17]
<img width="1173" alt="Снимок экрана 2023-05-12 в 12 46 49" src="https://github.com/russdreamer/instagram-followers-statistics/assets/85689621/02182fd8-d31a-4d2a-ac04-47b19e351d15">

Generating user's statistics might not work due to [instagram bug]
Error: Can not get whole followers list.

What is it? Is it possible to fix ut?

**Comment by russdreamer** [comment]
It’s related to [this bug.](https://github.com/russdreamer/instagram-followers-statistics/issues/14) I’ve reported to Instagram support, but they still hasn’t fixed it yet. Not all accounts affected by this bug.
It’s not possible to properly fix it in my application, but I can provide optional functionality to show statistics that is partly incorrect for the case when this bug occurs

**Comment by russdreamer** [comment]
@neklik should be solved. Please check
