### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'viewer')

### ISSUE THREAD

**Issue by Andrey-Pavlov-A** [russdreamer/instagram-followers-statistics#21]
Привет! После клика на Generate statistics получаю ошибку:
![image](https://github.com/russdreamer/instagram-followers-statistics/assets/80647405/a6491c79-25fe-400a-b420-e30ea6f966b6)

env: google 120.0.6099.110, windows 10

**Comment by IGVillainaire** [comment]
The same issue can be seen on a Windows 10 PC, Opera GX LVL 5 (core: 105.0.4970.63) version.

**Comment by lzrdblzzrd** [comment]
Эта же ошибка появляется, если выбрать заранее скачанный файл со статистикой.

**Comment by snake302** [comment]
the same for me

**Comment by russdreamer** [comment]
Instagram has just changed its website again 🙂 
Should be fixed now, please try again.
