### ISSUE TITLE
Перестало работать: Can not get whole followers list

### ISSUE THREAD

**Issue by neklik** [russdreamer/instagram-followers-statistics#3]
Выдаёт ошибку Error: Can not get whole followers list, когда пытаешься сгенерировать статистику 
<img width="1034" alt="Снимок экрана 2021-06-10 в 16 58 18" src="https://user-images.githubusercontent.com/85689621/121538139-36572b00-ca0d-11eb-9d99-ee8ff0ecb19c.png">

**Comment by russdreamer** [comment]
В этот раз Инстаграм передали свой API очень сильно. Постараюсь найти время и разобраться, как оно теперь работает

**Comment by neklik** [comment]
Спасибо!

**Comment by OlegSour** [comment]
Лучшее решение из всех что были. Жаль не работает больше(

**Comment by russdreamer** [comment]
Ребят, спасибо за приятные отзывы. Они смотивировали, чтоб найти время и пофиксить приложение. + оно стало быстрее.

**Comment by neklik** [comment]
Большое спасибо за ваш труд!!! 
Действительно работает теперь быстрее, и главное - работает 😍
