### ISSUE TITLE
Error: A link of script is not found.

### ISSUE THREAD

**Issue by andiskiy** [russdreamer/instagram-followers-statistics#5]
ошибка. не работает. Помогите, пожалуйста

<img width="1082" alt="Снимок экрана 2022-01-24 в 05 14 22" src="https://user-images.githubusercontent.com/17091892/150711351-587d3df0-df26-4d84-a8d4-8192a77a30c4.png">
.

**Comment by russdreamer** [comment]
Опишите, пожалуйста, шаги при которых возникает эта ошибка, браузер и его версию. И убедитесь, что залогинены в [инстаграм](https://www.instagram.com/).
У меня не получилось наткнуться на эту ошибку, возможно инстаграм потихоньку меняет их фронт.

**Comment by andiskiy** [comment]
> Опишите, пожалуйста, шаги при которых возникает эта ошибка, браузер и его версию. И убедитесь, что залогинены в [инстаграм](https://www.instagram.com/). У меня не получилось наткнуться на эту ошибку, возможно инстаграм потихоньку меняет их фронт.

Нажимаю просто кнопку "Генерировать статистику"
ОС macOS Monterey, версия 12.1 (21C52)
Браузер Chrome.
Версия 97.0.4692.99 (Официальная сборка), (x86_64)
в Инстаграм залогинен.

расширение переустанавливал, скрипт тоже.

**Comment by russdreamer** [comment]
Мне так и не удалось воспроизвести ошибку ни на одном из аккаунтов и браузере, почему-то подгружаются другие ресурсы. Раньше работало или это и были первые запуски приложения?  
Если ошибка так и осталась, то проверьте, что у вас в ресурсах.
Запустите в консоли команду: 
```
const regex = new RegExp("<script type=\"text/javascript\" src=.*?</script>", "g"); 
const matches = document.body.outerHTML.match(regex);
console.log(matches.join("\n"))
```
и пришлите сюда, что вам вывело. Скрипт ожидает, что будет ресурс по пути `static/bundles/es6/ConsumerLibCommons.js`

**Comment by russdreamer** [comment]
> > Опишите, пожалуйста, шаги при которых возникает эта ошибка, браузер и его версию. И убедитесь, что залогинены в [инстаграм](https://www.instagram.com/). У меня не получилось наткнуться на эту ошибку, возможно инстаграм потихоньку меняет их фронт.
> 
> Нажимаю просто кнопку "Генерировать статистику" ОС macOS Monterey, версия 12.1 (21C52) Браузер Chrome. Версия 97.0.4692.99 (Официальная сборка), (x86_64) в Инстаграм залогинен.
> 
> расширение переустанавливал, скрипт тоже.

Мне так и не удалось воспроизвести ошибку ни на одном из аккаунтов и браузере, почему-то подгружаются другие ресурсы. Раньше работало или это и были первые запуски приложения?  
Если ошибка так и осталась, то проверьте, что у вас в ресурсах.
Запустите в консоли команду: 
```
const regex = new RegExp("<script type=\"text/javascript\" src=.*?</script>", "g"); 
const matches = document.body.outerHTML.match(regex);
console.log(matches.join("\n"))
```
и пришлите сюда, что вам вывело. Скрипт ожидает, что будет ресурс по пути `static/bundles/es6/ConsumerLibCommons.js`

**Comment by russdreamer** [comment]
Мне так и не удалось воспроизвести ошибку ни на одном из аккаунтов и браузере, почему-то подгружаются другие ресурсы. Раньше работало или это и были первые запуски приложения?  
Если ошибка так и осталась, то проверьте, что у вас в ресурсах.
Находясь на сайте инстаграма, залогиневшись, запустите в консоли команду: 
```
const regex = new RegExp("<script type=\"text/javascript\" src=.*?</script>", "g"); 
const matches = document.body.outerHTML.match(regex);
console.log(matches.join("\n"))
```
и пришлите, пожалуйста, сюда, что вам вывело. Скрипт ожидает, что будет ресурс по пути `static/bundles/es6/ConsumerLibCommons.js`

**Comment by vladislavkaverin** [comment]
Версия 98.0.4758.102 (Официальная сборка), (64 бит)

**Comment by vladislavkaverin** [comment]
Давно пользуюсь расширением, сейчас возникла эта ошибка. 
Версия Chrome 98.0.4758.102 (Официальная сборка), (64 бит). 
![3cfb80bbc3](https://user-images.githubusercontent.com/34945367/154847046-8054185a-dabc-4068-9af9-01caa155b00e.jpg)

**Comment by russdreamer** [comment]
Во, теперь ясно, что они начали менять. А в приложении та же ошибка, что в первом сообщении? «a link of script is not found»? Если да, то как доберусь до компа, выкачу возможное исправление.

**Comment by vladislavkaverin** [comment]
> Во, теперь ясно, что они начали менять. А в приложении та же ошибка, что в первом сообщении? «a link of script is not found»? Если да, то как доберусь до компа, выкачу возможное исправление.

Да, ошибка та же - «A link of script is not found»

**Comment by russdreamer** [comment]
@vladislavkaverin обновил скрипт, проверьте сейчас. Если ещё не работает, покажите, есть ли ошибки в консоли

**Comment by vladislavkaverin** [comment]
Всё работает! Спасибо! 

p.s. было бы круто, если бы у проекта были реквизиты и каждый желающий мог отблагодарить тебя донатом :)

**Comment by russdreamer** [comment]
@vladislavkaverin спасибо огромное за желание отблагодарить, но пока мне хватит ваших отзывов 🙂
Добавил кнопку фидбека в приложение и ещё несколько фич на будущее, если будут проблемы в приложении или обновления.

**Comment by russdreamer** [comment]
[The issue is solved](https://github.com/russdreamer/instagram-followers-statistics/commit/ec85a014494a6fa00268da4d3b2bb82ae5094b72)
