### ISSUE TITLE
following statistics over time

### ISSUE THREAD

**Issue by raven428** [russdreamer/instagram-followers-statistics#6]
Привет! Спасибо за прекрасное расширение 🙂 А не могли бы доделать к нему помимо "Followers statistics over time" ещё и "Following statistics over time"? Очень не хватает чтобы можно было следить не только за подписчиками, а ещё и подписками. В добавлении к "Hidden functionality" это было бы прям киллер-фичой для сталкера 😆

Заранее спасибо!

**Comment by russdreamer** [comment]
Привет, ну, давай оставлю пока топик открытым, если будут ещё желающие, то реализую :)

**Comment by russdreamer** [comment]
Фича добавлена 🙂

**Comment by russdreamer** [comment]
Фича добавлена 🙂
