### ISSUE TITLE
Name of exported file

### ISSUE THREAD

**Issue by misterperfectman** [russdreamer/instagram-followers-statistics#8]
Is there a possibility that you can include the username, of which the followers and following are exported, to the JSON file name?

Like this:
**USERNAME**_followers_15_03_2022, 19_29_55.json

**Comment by russdreamer** [comment]
Yeah, great point! I'll implement it. In general, it's time to change json name as it's not just followers anymore

**Comment by russdreamer** [comment]
@misterperfectman done. Let me know if everything works as you expected

**Comment by misterperfectman** [comment]
@russdreamer it works perfectly. Thank you!
