### ISSUE TITLE
Error: Number of followers is not found. Make sure the given Username exists and you are logged in.

### ISSUE THREAD

**Issue by mikezp** [russdreamer/instagram-followers-statistics#9]
День добрый.

При нажатии кнопки (в Chrome) Generate Statistics возникает ошибка Number of followers is not found. Make sure the given Username exists and you are logged in. После чего кнопка Open App перестает отображаться. Не понимаю какая тут связь, но тем не менее :)

P.S.  В Firefox кнопка Open App перестала отображатсья какое-то время назад. Т.е. из Firefox зайти в приложение не получается. Поэтому перешел в Chrome.

**Comment by russdreamer** [comment]
Там две проблемы, просто в разных браузерах защита отрабатывает по-разному. 
Первая - они чуть усилили защиту изменения их страницы, из-за чего кнопка переставала отображаться.
Вторая - они изменили API сайта и нужно другими способами искать подписчиков и прочую инфу. 
Гляну детальнее на выходных

**Comment by russdreamer** [comment]
Fixed. Need to update the application.
Исправлено. Необходимо обновление приложения.
